name: CICD
on:
  push:

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Deploy code in heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.3 # This is the action
        with:
          email: "alexandru.poboranu@stud.acs.upb.ro"
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: "foodini-dss" #Must be unique in Heroku
          dockerfile_path: "."
